[technote]
id = "RTN-079"
series_id = "RTN"
canonical_url = "https://rtn-079.lsst.io"
github_url = "https://github.com/lsst/rtn-079"
github_default_branch = "main"
date_created = 2024-04-08T16:06:46Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "deprecated"
note = "This document is now being published as RTN-086."

[[technote.status.supersceding_urls]]
title = "RTN-086: Bulk Data Transfer Policies and Procedures"
url = "https://rtn-086.lsst.io/"

[[technote.authors]]
name.given = "Richard"
name.family = "Dubois"
internal_id = "duboisr"

[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
address = "2575 Sand Hill Rd., Menlo Park, CA 94025, USA"
